# 元智能体配置示例
agent:
  name: "MetaAgent"
  id: "meta-agent-001"
  type: "meta"
  version: "1.0.0"

capabilities:
  name: "MetaAgent"
  description: "系统元智能体，负责协调和管理所有智能体"
  input_types: ["system_management", "task_allocation", "agent_monitoring"]
  output_types: ["coordination", "management", "monitoring"]
  max_concurrent_tasks: 10
  specializations: ["system_coordination", "task_scheduling", "resource_management"]

configuration:
  # 监控配置
  monitoring_interval: 30  # 秒
  health_check_interval: 60  # 秒

  # 任务分配配置
  allocation_strategy: "load_balanced"  # load_balanced, priority, capability_matched
  max_pending_tasks: 10000
  task_timeout: 3600  # 秒

  # 系统管理配置
  auto_recovery: true
  max_agent_instances: 100
  system_backup_interval: 3600  # 秒

  # 决策配置
  decision_timeout: 30  # 秒
  risk_assessment_enabled: true
  load_balancing_threshold: 0.8

dependencies:
  - "redis"
  - "postgresql"
  - "message_bus"
  - "monitoring_system"

resources:
  memory_mb: 1024
  cpu_cores: 4
  storage_gb: 20
  network_bandwidth_mbps: 100

security:
  authentication_required: true
  authorization_level: "system_admin"
  encryption_enabled: true
  audit_logging: true

performance:
  metrics_collection_interval: 60  # 秒
  performance_history_retention: 7  # 天
  optimization_enabled: true
  auto_scaling_enabled: false