# 开发环境配置

# 继承默认配置并覆盖特定设置
extends: "default.yaml"

# 系统配置
system:
  debug: true
  log_level: "DEBUG"

# 服务器配置
server:
  host: "127.0.0.1"
  port: 8000
  workers: 1

# 消息总线配置
message_bus:
  max_queue_size: 100
  processing_interval_seconds: 0.1

# 智能体注册表配置
agent_registry:
  heartbeat_timeout_seconds: 60
  cleanup_interval_seconds: 30

# 任务管理器配置
task_manager:
  max_concurrent_tasks: 10
  default_timeout_seconds: 300
  task_retention_days: 7

# 资源管理器配置
resource_manager:
  monitoring_interval_seconds: 30
  rebalance_interval_seconds: 120

# 监控配置
monitoring:
  enabled: true
  monitoring_interval_seconds: 10
  performance_tracking:
    enabled: true
    detailed_logging: true

# 日志配置
logging:
  level: "DEBUG"
  console_output: true
  file: "logs/development.log"

# API配置
api:
  cors_enabled: true
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  rate_limiting:
    enabled: false

# 健康检查配置
health_check:
  enabled: true
  detailed_response: true