# 生产环境配置

# 继承默认配置并覆盖特定设置
extends: "default.yaml"

# 系统配置
system:
  debug: false
  log_level: "WARNING"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  workers: 8
  timeout: 600
  max_connections: 5000

# 消息总线配置
message_bus:
  max_queue_size: 5000
  processing_interval_seconds: 0.001
  max_message_size_mb: 50

# 智能体注册表配置
agent_registry:
  heartbeat_timeout_seconds: 120
  cleanup_interval_seconds: 120
  max_agents: 1000

# 任务管理器配置
task_manager:
  max_concurrent_tasks: 500
  default_timeout_seconds: 7200
  retry_attempts: 5
  task_retention_days: 90

# 资源管理器配置
resource_manager:
  monitoring_interval_seconds: 30
  rebalance_interval_seconds: 300
  default_agent_limits:
    max_concurrent_tasks: 10
    max_cpu_usage: 90.0
    max_memory_usage: 85.0

# 监控配置
monitoring:
  enabled: true
  metrics_retention_hours: 168  # 7 days
  alerts_retention_days: 30
  monitoring_interval_seconds: 15
  performance_tracking:
    enabled: true
    detailed_logging: false

# 数据库配置
database:
  enabled: true
  type: "postgresql"
  connection_string: "postgresql://user:password@localhost:5432/agent_system"
  pool_size: 20
  max_overflow: 40

# Redis配置
redis:
  enabled: true
  host: "localhost"
  port: 6379
  db: 0
  password: "your-redis-password"
  max_connections: 20

# 安全配置
security:
  authentication:
    enabled: true
    method: "token"
    secret_key: "${SECRET_KEY}"  # 从环境变量读取
  authorization:
    enabled: true
  ssl:
    enabled: true
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"

# 日志配置
logging:
  level: "INFO"
  console_output: false
  file: "/var/log/agent_system/app.log"
  max_size_mb: 500
  backup_count: 10
  structured_logging: true

# API配置
api:
  cors_enabled: false
  rate_limiting:
    enabled: true
    requests_per_minute: 120
  documentation:
    enabled: false

# 健康检查配置
health_check:
  enabled: true
  interval_seconds: 15
  timeout_seconds: 5
  detailed_response: false